on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Build and Push to ECR

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and Push to ECR
        with:
          image: nizuri
          registry: 526286878664.dkr.ecr.us-west-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}